version: '3'
services:
  app:
    restart: always
    build: src
    ports:
      - '10060:9292'
    volumes:
      - ./src:/app
    environment:
      - FLAG=SWCTF{now_listening_algorithmic_everyday}
